waituntil {!(IsNull (findDisplay 46))};
waituntil {!isNil "CBA_fnc_addKeyHandler"};
[(KeybindingsDone select 0 select 1), (KeybindingsDone select 0 select 2),{call KeyPress6; true}, "keydown", "101"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 3 select 1),(KeybindingsDone select 3 select 2),{call KeyPressY; true}, "keydown", "103"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 1 select 1), (KeybindingsDone select 1 select 2),{call KeyPress7; true}, "keydown", "104"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 4 select 1),(KeybindingsDone select 4 select 2),{call KeyPressF5;true}, "keydown", "105"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 5 select 1),(KeybindingsDone select 5 select 2),{call keys_toggle;true}, "keydown", "106"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 6 select 1),(KeybindingsDone select 6 select 2),{call KeyPressT;true}, "keydown", "107"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 7 select 1),(KeybindingsDone select 7 select 2),{call KeyPressE;false}, "keydown", "108"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 8 select 1),(KeybindingsDone select 8 select 2), {call KeyPressF;false}, "keydown", "109"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 9 select 1),(KeybindingsDone select 9 select 2),{call KeyPressSpaceBar;true}, "keydown", "110"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 10 select 1), (KeybindingsDone select 10 select 2),{call KeyPress1;true}, "keydown", "111"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 11 select 1),(KeybindingsDone select 11 select 2),{call KeyPress3;true}, "keydown", "112"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 12 select 1),(KeybindingsDone select 12 select 2), {call KeyPressShift;false}, "keydown", "113"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 13 select 1),(KeybindingsDone select 13 select 2),{call KeyPressF4;true}, "keydown", "114"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 64 select 1),(KeybindingsDone select 64 select 2),{call KeypressHolsterPistol; true}, "keydown", "115"] call CBA_fnc_addKeyHandler;
[(KeybindingsDone select 65 select 1),(KeybindingsDone select 65 select 2),{call KeypressHolsterRifle; true}, "keydown", "116"] call CBA_fnc_addKeyHandler;